# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skmgr < Formula
  desc "The framework-agnostic skill manager for AI agents"
  homepage "https://github.com/AbhishekGawade1999/skmgr"
  version "1.0.0"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AbhishekGawade1999/skmgr/releases/download/v1.0.0/skmgr_Darwin_x86_64.tar.gz"
      sha256 "d757a2d171a3bed03015160806b2d61591a87003af1e9b60d303631594449758"

      define_method(:install) do
        bin.install "skmgr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AbhishekGawade1999/skmgr/releases/download/v1.0.0/skmgr_Darwin_arm64.tar.gz"
      sha256 "9f786f96d62738eeb75e0f8cce88b84f2729a86c3525774230a3467f7ec5e844"

      define_method(:install) do
        bin.install "skmgr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AbhishekGawade1999/skmgr/releases/download/v1.0.0/skmgr_Linux_x86_64.tar.gz"
      sha256 "7e6f69e68db08652a44e9693824d3cd44dea687eeb613f3e86d4e3ec5f43b51a"
      define_method(:install) do
        bin.install "skmgr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AbhishekGawade1999/skmgr/releases/download/v1.0.0/skmgr_Linux_arm64.tar.gz"
      sha256 "58bab647ba863d8bf841917a770ebb841e641d6106b3ef96db45b2c0ae803023"
      define_method(:install) do
        bin.install "skmgr"
      end
    end
  end

  test do
    system "#{bin}/skmgr version"
  end
end
